model = "gpt-5"
model_reasoning_effort = "high"

[mcp_servers.dataworks]
command = "/Users/lix18854/.pyenv/versions/3.13.2/bin/python"
args = ["/Users/lix18854/Documents/code/my_dataworks_mcp/simple_mcp.py"]

# 命理MCP服务 - 正确配置
[mcp_servers.mingli]
command = "mingli-mcp"
startup_timeout_sec = 20

[mcp_servers.mingli.env]
TRANSPORT_TYPE = "stdio"
LOG_LEVEL = "ERROR"

[mcp_servers.chrome-devtools]
command = "chrome-devtools-mcp"
args = []

[projects."/Users/lix18854/Documents/code/my_dataworks_mcp"]
trust_level = "trusted"

[projects."/Users/lix18854/Documents/sql/sql_scripts"]
trust_level = "trusted"

[projects."/Users/lix18854/Documents/code/snake"]
trust_level = "trusted"

[projects."/Users/lix18854/Documents/code/llove"]
trust_level = "trusted"

[projects."/Users/lix18854/Documents/code/ziwei_mcp"]
trust_level = "trusted"
